version: "3.9"

services:

  vosk:
    container_name: vosk-server
    build: ./
    platform: linux/arm64
    ports:
      - "2700:2700"
    expose:
      - "2700"
    command: ["gunicorn", "--config", "gunicorn_config.py", "server:app"]
    restart: on-failure
    networks:
      - default
